### PR TITLE
add timestamp to a game object when it is updated

### PR DESCRIPTION
**Pull request by pbredenberg**
Initially I thought I'd look for a timestamp and if it exists add an updatedTimestamp, but then it seemed safer to look for an ID, since that's what's required to overwrite a game object. Could go either way, because if the timestamp isn't provided look like it'll be overwritten anyway.

This way, we at least have a property that will be there ONLY if the record is updated.

### CODE REVIEW

**Review by onebytegone — CHANGES_REQUESTED** [review]
Sounds like a good idea! From a data consistency standpoint, what do you think about having both a `created` and `lastUpdated` timestamp? When `created === lastUpdated`, it would indicate that the game hadn't been modified after creation.

**Comment by onebytegone** [comment]
Wow, I totally forgot my own code here. That comment is way off. I need more sleep...

**Comment by pbredenberg** [comment]
Yeah I think that's a better approach. Did a little refactoring. Check it again with the latest commit plz.

**Review by onebytegone — APPROVED** [review]
Looks good!

**Pull request merged**
